#version 430 core

// we use the following block to define constants
// this way our IDE knows which constants to expect
// but we can still replace them
#ifndef default_consts
#endif // default_consts

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout (rgba32f) uniform image2D A;
layout (std430) buffer shader_data {
    float color;
};

void main() {
    ivec2 position = ivec2(gl_WorkGroupID.xy);
    imageStore(A, position, vec4(color, color, color, 1.0));
}